In [25]:
# Optional Lab: Python Numpy and Vecotorization
#importing necessory modules

import numpy as np
import time

In [26]:
# Vector Creation

# NumPy routines which allocate memory and fill arrays with value
a = np.zeros(4);                print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4,));             print(f"np.zeros(4,) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4); print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")


# NumPy routines which allocate memory and fill arrays with value but do not accept shape as input argument
a = np.arange(4.);              print(f"np.arange(4.):     a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.rand(4);          print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

# NumPy routines which allocate memory and fill with user specified values
a = np.array([5,4,3,2]);  print(f"np.array([5,4,3,2]):  a = {a},     a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5.,4,3,2]); print(f"np.array([5.,4,3,2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4,) :  a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [0.65615492 0.10218022 0.87509598 0.10287701], a shape = (4,), a data type = float64
np.arange(4.):     a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4): a = [0.49977959 0.69575399 0.39189026 0.33525598], a shape = (4,), a data type = float64
np.array([5,4,3,2]):  a = [5 4 3 2],     a shape = (4,), a data type = int64
np.array([5.,4,3,2]): a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


In [30]:
# Indexing and Slicing

a = np.arange(10)
print (a)

# access an element

print (a[2].shape) #scaler
print (a[2])

# negative indexes count from the end

print (a[-1])

#slicing
print ('Slicing')
b = np.arange(11)

print (b)

#access consecutive elements
c = b[2:7:1]
print (c)

#access all elements above 3
c = b[3:]
print (c)


#access all elements below 3

c = b[:3]
print (c)




[0 1 2 3 4 5 6 7 8 9]
()
2
9
Slicing
[ 0  1  2  3  4  5  6  7  8  9 10]
[2 3 4 5 6]
[ 3  4  5  6  7  8  9 10]
[0 1 2]


In [31]:
#number of single vector applications, listing a few

a = np.arange(12)
print (a)

# negate the elements of vector a

b = -a
print (b)


#sum of all elements of the vector

b = np.sum(a)
print (b)

#mean of all elements

b = np.mean(a)
print (b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[  0  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10 -11]
66
5.5


In [33]:
# We utilized the NumPy library because it improves speed memory efficiency. Let's demonstrate:

def my_dot(a, b): 
    """
   Compute the dot product of two vectors
 
    Args:
      a (ndarray (n,)):  input vector 
      b (ndarray (n,)):  input vector with same dimension as a
    
    Returns:
      x (scalar): 
    """
    x=0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x

np.random.seed(1)
a = np.random.rand(10000000)  # very large arrays
b = np.random.rand(10000000)

tic = time.time()  # capture start time
c = np.dot(a, b)
toc = time.time()  # capture end time

print(f"np.dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ")

tic = time.time()  # capture start time
c = my_dot(a,b)
toc = time.time()  # capture end time

print(f"my_dot(a, b) =  {c:.4f}")
print(f"loop version duration: {1000*(toc-tic):.4f} ms ")

del(a);del(b)  #remove these big arrays from memory

np.dot(a, b) =  2501072.5817
Vectorized version duration: 2.6729 ms 
my_dot(a, b) =  2501072.5817
loop version duration: 2480.6631 ms 
